### ISSUE TITLE
Possible bug when bidirectionally binding among sibling components.

### ISSUE THREAD

**Issue by Alfredo-Delgado** [canjs/can-stache-bindings#325]
Creating this issue for further investigation.

In this example, `<source-component />` sets a default person whenever `person` is cleared and `<clear-button />` can clear `person`.

```
<h3>Hello [demoContext/{{./person}}]</h3>
  
<source-component {(person)}="./person" />
<clear-button {(person)}="./person" />
```

After `<clear-button />` is clicked, the default person set by `<source-component />` isn't propagated to its parent scope or back to `<clear-button />`.

![licecap](https://user-images.githubusercontent.com/798836/31949473-66df534a-b8a7-11e7-8f84-d339e3f42cbd.gif)

Here's the code: https://codepen.io/Alfredo-Delgado/pen/rGExOg?editors=1011

**Comment by Sinjhin** [comment]
This is actually behaving as expected in `3.x`. The bindingSemaphore is used internally to prevent cyclic bindings and the parent takes priority, only allowing itself to be changed (and propagate those changes down) once.

When the clear-button component sets person to empty string, the parent gets this change and sets both the source-component and clear-button component to empty string (as well as itself).

When the source component gets set to an empty string the setter actually returns the `defaultPerson` "John". This does not change the parent and then propagate changes down because the parent has already been changed in this batch of changes.

A test for this working properly (changing all values to "John" and keeping them in sync) has been written here: https://github.com/canjs/can-stache-bindings/pull/348

And is merged into the current major branch.
