### ISSUE TITLE
Setting element attribute causes viewmodel prop to be set

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-bindings#336]
In [this JS Bin](https://jsbin.com/rujocijibu/1/edit?html,js,console,output), you can see the style being changed on the component’s element. This causes the `style` property to be set on the ViewModel, which throws an error because it’s sealed.

This currently is an issue in can-stache-bindings 3.11.0

**Comment by phillipskevin** [comment]
After talking with @imaustink, I realized that setting attributes on components causes the property to be set on the viewModel so that you can set string properties on your viewModel.

This makes stuff like this work:
```
<my-modal modelId="1" /> 
```

I think the solution to this is to:
- [x] 1. make sure `modelId:from="'1'"` works to set `modelId` to the string `"1"` on the viewModel
- [x] 2. warn people doing `modelId="1"` on components to use `modelId:from="'1'"`
- [x] 3. in 4.0, make `style="color: red"` not set attributes on viewModels

This is related to https://github.com/canjs/can-view-parser/issues/77.

**Comment by phillipskevin** [comment]
For `#3`, this code was removed in `major`: https://github.com/canjs/can-stache-bindings/blob/23999787400e49697d4a32b51bbb6ca1d53d6248/can-stache-bindings.js#L1083-L1186

Specifically, the `isAttributeToChild` branch was what caused viewmodel properties to be set from attributes.
