### ISSUE TITLE
:to bindings for functions are not bound to the correct this

### ISSUE THREAD

**Issue by matthewp** [canjs/can-stache-bindings#493]
For example:

```js
<audio src="/song.mp3" play:to="play">
```

Calling the `play()` function here will through because it is not bound to the element.

**Comment by justinbmeyer** [comment]
The problem is that: https://github.com/canjs/can-attribute-observable/blob/3475666f8f84428d40c8e30e4f3611032820a953/behaviors.js#L507

Should be doing the binding probably.


... check if the prop is a function ... if it is ... call `.bind()`.

Maybe better would be to check if a function up the proto chain and then do `.bind()`, but that's probably not necessary .. or better ...

**Comment by matthewp** [comment]
The downside to binding is that you can never `.call` or `.apply` that function. I think there should be a syntactical way to say that you want the function bound.

**Comment by matthewp** [comment]
I think we should fix this bug since `:from` has it be bound. But I think this is not the ideal behavior and should be changed in a major version.

**Comment by justinbmeyer** [comment]
Why major? We do this for bindings in the other direction.

**Comment by matthewp** [comment]
I think the current behavior is not ideal for either to or from. I think we should, for now, make them match.  For backwards compat we should leave it that way, but some syntactical method for getting non-bound methods would also be nice.

**Comment by justinbmeyer** [comment]
I think it’s ideal because users want this 99% of the time as components are view-model oriented. If we had functions that needed other “this”s more often, I’d agree. Those passed functions always want the “this” to be the “this” of the originating ViewModel.
