### ISSUE TITLE
Event Simple Setter ~13

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#6]
From:
- https://github.com/canjs/canjs/issues/1088 - Make it possible to have two way {($value)} bindings update on `input` event
- https://github.com/canjs/canjs/issues/1984 - Event simple setter

An ideal solution to this would be making something like:

```
<input value:bind="name"/>
```

Work on input like:

```
<input value:from="name" on:enter="name = scope.element.value"/>
```

Anyone have a good alternate proposal?  Vuejs does it this way.

**Comment by taai** [comment]
@justinbmeyer I have done something like this for existing project, and it works out of the box, it's not just a concept.

viewModel with list of languages and a item model with translatable values:

```
{
    langs: [
        { langCode: 'en', langName: 'English' },
        { langCode: 'es', langName: 'Spanish' }
    ],
    model: {
        color: 'red',
        en: { title: '', description: '' },
        es: { title: '', description: '' }
    }
}
```

template:

```
{{#each langs}}
    <input {($value)}="model.{{langCode}}.title">
{{/each}}
```

It binds the values to _viewModel_ by using generated keys. So the `model.{{langCode}}.title` converts to `model.en.title` and that's the key in the _viewModel_ the value of the input will be bind to.
So, I don't see a problem with setting the key name just by doing this:

```
<input {($value)}="{{valueThatShouldBeUsedAsKey}}">
```

.
..
...

About using different event for value changes instead of binding to `change` event... I like this syntax:

```
<input {($value,enter)}="name"/>
```

The second parameter (in this case `enter`) is very convenient.
For example, if you would write it with the default `change` event, it is very self explanatory:

```
<input {($value,change)}="name"/>
```

**Comment by justinbmeyer** [comment]
> <input {($value)}="model.{{langCode}}.title">

That wouldn't work for setting a value in an event binding. This is the primary goal.

**Comment by taai** [comment]
@justinbmeyer What do you mean with "event binding"? It is working! Here, have a look – http://jsbin.com/mokagalape/edit?html,js,output

**Comment by justinbmeyer** [comment]
I mean listen to a specific event and set a value, not two way binding. 

($click)="%viewModel.someMethod() as propName"

**Comment by leoj3n** [comment]
I might be misunderstanding, but for reference I think this is how Polymer does something similar:

`target-prop="{{hostProp::target-change-event}}"`

https://www.polymer-project.org/2.0/docs/devguide/data-binding#two-way-native

**Comment by justinbmeyer** [comment]
```
expr.hashes[0].key //->  "abc"
expr.hashes[0].value() //-> observable<zed>


scope.set(key, expr.hashes[0].value().value )
```
